- id: ems-esp_offline
  alias: See if ems-esp goes offline
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.ems_esp_status
    to: offline
  action:
    - service: notify.admin_notify
      data_template:
        title: EMS-ESP
        message: 'gone offline'
          
- id: boiler_shower
  alias: Alert shower time
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.last_shower_duration
  action:
  - service: notify.emsesp_notify
    data_template:
      title: Shower finished at {{states.sensor.time.state}}
      message: "{{ states.sensor.last_shower_duration.state }}"
      