title: Home
views:
  - id: home
    # add you stuff here

  - id: ems-esp_id0
    title: Heating
    cards:
      - id: ems-esp_id1
        type: glance
        entities:
          - entity: binary_sensor.tap_water
            icon: mdi:fire
          - entity: binary_sensor.heating
            icon: mdi:radiator
      - id: ems-esp_id2
        type: entities
        title: Boiler
        show_header_toggle: false
        entities:
          - entity: sensor.boiler_boottime
            icon: mdi:clock-start
          - entity: sensor.boiler_updated
            icon: mdi:update
          - entity: sensor.ems_esp_status
            icon: mdi:electric-switch
          - type: divider
          - entity: sensor.warm_water_selected_temperature
          - entity: sensor.warm_water_current_temperature
            icon: mdi:coolant-temperature
          - entity: sensor.warm_water_activated
            icon: mdi:water-boiler
          - entity: sensor.warm_water_3_way_valve
            icon: mdi:valve
          - type: divider
          - entity: sensor.boiler_temperature
          - entity: sensor.return_temperature
          - entity: sensor.current_flow_temperature
            icon: mdi:coolant-temperature
          - entity: sensor.pump_modulation
            icon: mdi:wave
          - entity: sensor.ignition
            icon: mdi:flash-alert
          - entity: sensor.gas
            icon: mdi:gas-cylinder
          - entity: sensor.fan
            icon: mdi:fan
          - entity: sensor.boiler_pump
            icon: mdi:water-pump
          - entity: sensor.system_pressure
            icon: mdi:water-boiler
          - entity: sensor.burner_max_power
            icon: mdi:fire
          - entity: sensor.burner_current_power
            icon: mdi:fire
      - id: ems-esp_id3
        type: vertical-stack
        cards:
          - type: entities
            title: Shower Monitor
            show_header_toggle: false
            entities:
              - entity: switch.shower_timer
                icon: mdi:timer
              - switch.long_shower_alert
              - type: divider
              - entity: sensor.last_shower_duration
                icon: mdi:clock-start
              - entity: sensor.showertime_time
                icon: mdi:timelapse
          - type: entity-button
            icon: mdi:shower-head
            name: send a cold shot of shower water
            entity: script.shower_coldshot
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.shower_coldshot
